baseURL = 'https://ebecuaaii.github.io/blogcuatruc.github.io/'
languageCode = 'en-us'
title = 'Learning Java & JavaScript with me'
theme = 'hextra'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Portfolio"
    url = "https://my-portfolio-nine-lac-34.vercel.app/"
    weight = 3

