[build]
  publish = "public"
  command = "hugo --gc --minify --themesDir themes"

[build.environment]
  HUGO_VERSION = "0.128.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  GIT_SUBMODULE_STRATEGY = "recursive"