[build]
  command = "hugo mod tidy && hugo --gc --minify --themesDir themes"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.128.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  GIT_SUBMODULE_STRATEGY = "recursive"
