[build]
  command = "rm -rf themes/hugo-clarity && git clone https://github.com/chipzoller/hugo-clarity.git themes/hugo-clarity && hugo --gc --minify --environment production"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.151.0"
  GO_VERSION = "1.22.2"
