[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "post/rich-content/"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Me"
  identifier = "Me"
  weight = -108
[[main]]
  parent = "Me"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/nguyen-ho-ngoc-truc-37075133b/"
[[main]]
  parent = "Me"
  name = "Portfolio"
  url = "https://my-portfolio-nine-lac-34.vercel.app/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/ebecuaaii"
[[social]]
  name = "portfolio"
  weight = 2
  url = "https://my-portfolio-nine-lac-34.vercel.app/"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/#"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
# name = "bluesky"
# url = "https://bsky.app/profile/#"